val auto_fill : Ecaml.Minor_mode.t
val semantic : Ecaml.Minor_mode.t
val smerge : Ecaml.Minor_mode.t
val global_whitespace : Ecaml.Minor_mode.t
val tool_bar : Ecaml.Minor_mode.t
val menu_bar : Ecaml.Minor_mode.t
val scroll_bar : Ecaml.Minor_mode.t
val column_number : Ecaml.Minor_mode.t
val global_subword : Ecaml.Minor_mode.t
val delete_selection : Ecaml.Minor_mode.t
val electric_indent : Ecaml.Minor_mode.t
val electric_pair : Ecaml.Minor_mode.t
val show_paren : Ecaml.Minor_mode.t
val savehist : Ecaml.Minor_mode.t
val winner : Ecaml.Minor_mode.t
val fido_vertical : Ecaml.Minor_mode.t
val minibuffer_depth_indicate : Ecaml.Minor_mode.t
val global_auto_revert : Ecaml.Minor_mode.t
val diff : Ecaml.Minor_mode.t
val flyspell : Ecaml.Minor_mode.t
val reftex : Ecaml.Minor_mode.t
val auto_insert : Ecaml.Minor_mode.t
val global_goto_address : Ecaml.Minor_mode.t
val make : ?variable_name:string -> string -> Ecaml.Minor_mode.t
