alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias lal='ls -Al'
alias up='sudo apt-get update && sudo apt-get upgrade'
alias opamup='opam update && opam upgrade'
alias mr-fetch-all='mr -j 4 -d ~ -c ~/.mrconfig fetch'
