alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias lal='ls -Al'
alias up='sudo apt update && sudo apt upgrade'
alias opamup='opam update -u'
alias mr-fetch-all='mr -j 4 -d ~ -c ~/.mrconfig fetch'
